name: Dashboard e2e testing

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  cypress:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2

      - run: yarn add

      - run: yarn build
        env:
          NODE_ENV: production

      - name: Run project locally
        run: |
          yarn add serve
          $(yarn bin)/serve dist -s -p 8080 &
      - name: Run tests
        uses: cypress-io/github-action@v2
        with:	
          browser: chrome
          headless: true